#!/usr/bin/perl

#my $tel = '79262674877';
my $line = $ARGV[0]; 
my $ussd = $ARGV[1]; # '*102#';

my $cmd='curl "http://goip1.stelsdev.ru/default/en_US/ussd_info.html?type=ussd" -H "Pragma: no-cache" -H "Origin: http://goip1.stelsdev.ru" -H "Accept-Encoding: gzip,deflate" -H "Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4,uk;q=0.2" -H "Authorization: Basic YWRtaW46MDBzdGVscw==" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cache-Control: no-cache" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36" -H "Connection: keep-alive" -H "Referer: http://goip1.stelsdev.ru/default/en_US/tools.html?type=ussd" --data "line=_line_&smskey=5418537a&action=USSD&telnum=*102"%"23&send=Send" --compressed';

$cmd =~ s/_line_/$line/;
$cmd =~ s/_tel_/$tel/;
$cmd =~ s/_text_/$text/;

system $cmd;
